# Generated by Django 5.2.6 on 2025-09-10 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_token"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("can_view_user_list", "Может просматривать список пользователей"),
                    ("can_block_user", "Может блокировать пользователей"),
                    ("can_view_user_stats", "Может просматривать статистику пользователей"),
                ],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
