# Generated by Django 5.2.6 on 2025-09-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "email",
                    models.EmailField(
                        help_text="Email адрес получателя", max_length=255, unique=True, verbose_name="Email адрес"
                    ),
                ),
                ("full_name", models.CharField(help_text="Полное имя получателя", max_length=200, verbose_name="ФИО")),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Дополнительная информация о получателе",
                        null=True,
                        verbose_name="Комментарий",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания получателя")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления получателя")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Включен ли получатель в рассылки", verbose_name="Активен"
                    ),
                ),
            ],
            options={
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
                "ordering": ["full_name", "-created_at"],
            },
        ),
    ]
