# Generated by Django 5.2.6 on 2025-09-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_mailing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(
                        help_text="Введите тему сообщения", max_length=150, verbose_name="Тема сообщения"
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="Введите текст сообщения", verbose_name="Содержание сообщения"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания сообщения")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления сообщения")),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="recipient",
            name="email",
            field=models.EmailField(max_length=255, unique=True, verbose_name="Email адрес"),
        ),
        migrations.AlterField(
            model_name="recipient",
            name="full_name",
            field=models.CharField(max_length=200, verbose_name="ФИО"),
        ),
        migrations.AlterField(
            model_name="recipient",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="(включен ли получатель в рассылки)", verbose_name="Активен"
            ),
        ),
    ]
