# Generated by Django 5.2.6 on 2025-09-07 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_mailing", "0002_message_alter_recipient_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(verbose_name="Содержание сообщения"),
        ),
        migrations.AlterField(
            model_name="message",
            name="title",
            field=models.CharField(max_length=150, verbose_name="Тема сообщения"),
        ),
        migrations.CreateModel(
            name="Mailing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Произвольное название рассылки для ее идентификации",
                        max_length=200,
                        null=True,
                        verbose_name="Название рассылки",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        help_text="Когда начать отправку рассылки", verbose_name="Дата и время начала отправки"
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        help_text="Когда завершить отправку рассылки", verbose_name="Дата и время окончания отправки"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("created", "Создана"), ("started", "Запущена"), ("completed", "Завершена")],
                        default="created",
                        help_text="Текущий статус рассылки",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания рассылки")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления рассылки")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Включена ли рассылка", verbose_name="Активна|Неактивна"
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        help_text="Сообщение для отправки",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mailings",
                        to="service_mailing.message",
                        verbose_name="Сообщение",
                    ),
                ),
                (
                    "recipients",
                    models.ManyToManyField(
                        help_text="Список получателей рассылки",
                        related_name="mailings",
                        to="service_mailing.recipient",
                        verbose_name="Получатели",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
                "ordering": ["-created_at"],
            },
        ),
    ]
